DROP DATABASE Lw11;
CREATE DATABASE Lw11;
USE Lw11;
CREATE TABLE messages
(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    user_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) 	NOT NULL,
    country VARCHAR(50)	NOT NULL,
    gender VARCHAR(100),
    message TEXT
);
SELECT * FROM messages;
